### ISSUE TITLE
doesn't support esm app

### ISSUE THREAD

**Issue by tjx666** [swandir/vite-plugin-http2-proxy#2]
reproduce:

1. git clone git@github.com:tjx666/vite-plugin-esm-issue.git
2. pnpm install
3. pnpm dev

<img width="977" alt="image" src="https://user-images.githubusercontent.com/41773861/220439005-f03a277c-0040-455d-ae7b-4f2ddaddeafb.png">

```
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 1.31 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/Library/Caches/fnm_multishells/34273_1677007298934/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/34273_1677007298934/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/34273_1677007298934/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.1.2 => 4.1.3 
    vite-plugin-http2-proxy: ^0.3.2 => 0.3.2 
```

**Comment by swandir** [comment]
Hey! Yeah, indeed. TSC with the current setup produces not quite valid output for dual cjs/esm consumption.

I've set up dual bundling with ESBuild.

Published in 0.4.0.
