### ISSUE TITLE
Plugin is stopping if the request takes time

### ISSUE THREAD

**Issue by edsonmartins** [swandir/vite-plugin-http2-proxy#3]
How can we set a timeout for requests? After reaching a certain amount of time, the plugin stops and we are forced to start the application again.

`node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5) {
  code: 'ECONNREFUSED',
  statusCode: 503,
  connectedSocket: false,
  reusedSocket: false,
  [errors]: [
    Error: connect ECONNREFUSED ::1:8443
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8443
    },
    Error: connect ECONNREFUSED 127.0.0.1:8443
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 8443
    }
  ]
}

Node.js v20.9.0
error Command failed with exit code 1.`

**Comment by swandir** [comment]
I've added `timeout` option.

It defaults to 30 seconds (to match the browser), so you might not need to set it.

Published in 0.4.2
