### ISSUE TITLE
add  vite 5.0 peer dependency suppoert, or just remove vite peer dependency 

### ISSUE THREAD

**Issue by q1uxu** [swandir/vite-plugin-http2-proxy#4]
when i install this dependency, the console output is below: 
```console
 WARN  Issues with peer dependencies found
.
└─┬ vite-plugin-http2-proxy 0.4.2
  └── ✕ unmet peer vite@"^2.9.12 || ^3.0.0 || ^4.0.0": found 5.3.1
```
add peer dependency vite 5.0 suppoert, or just remove vite peer dependency

**Comment by swandir** [comment]
Yeah, it seems Vite 5 can be supported without code changes. Published in 0.4.3.
