### ISSUE TITLE
Vite 6

### ISSUE THREAD

**Issue by Sverri** [swandir/vite-plugin-http2-proxy#6]
Current versions:
"vite": "5.4.11",
"vite-plugin-http2-proxy": "0.4.3",

$ npm install --save-dev --save-exact vite@latest

npm warn Could not resolve dependency:
npm warn peer vite@"^2.9.12 || ^3.0.0 || ^4.0.0 || ^5.0.0" from vite-plugin-http2-proxy@0.4.3

**Comment by swandir** [comment]
Published as 0.5.0
